//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Brainvest.DscribeQuickStart1.Business {
	using System;
	using Microsoft.EntityFrameworkCore;
	using Brainvest.Dscribe.Abstractions;
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
	using Newtonsoft.Json;
	
	
	public partial class BusinessDbContext : Microsoft.EntityFrameworkCore.DbContext {
		
		public BusinessDbContext(DbContextOptions options) : 
				base(options) {
		}
	}
	
	[System.Composition.ExportAttribute(typeof(IBusinessRepositoryFactory))]
	public partial class DbContextFactory : IBusinessRepositoryFactory {
		
		public virtual IDisposable GetDbContext(DbContextOptions options){ return new BusinessDbContext(options); }
	}
}
